### ISSUE TITLE
Debian PKG

### ISSUE THREAD

**Issue by semiot** [media-explorer/media-explorer#46] opened 2011-06-18 16:17 UTC
Create a package for Debian.

**Comment by hbons** [comment] 2011-07-05 02:26
Fedora too!

**Comment by dlespiau** [comment] 2011-07-05 08:32
There's already a bug for that :p

**Comment by hadess** [comment] 2011-07-05 17:50
That's a dupe of #18.

**Comment by ghost** [comment] 2011-07-05 22:23
Ok closing

**Closed as completed by ghost** 2011-07-05 22:23 UTC
Labels: Feature, Medium
